id = "r"
name = "R"
version = "0.0.7"
schema_version = 1
authors = [
    "Owen Smith <owen8461@protonmail.com>",
    "Aymen Nasri <aymennasrii@proton.me>",
    "Changtao Li <60499240+lict99@users.noreply.github.com>",
]
description = "R languange support"
repository = "https://github.com/ocsmit/zed-r"

[grammars.r]
repository = "https://github.com/r-lib/tree-sitter-r"
commit = "c55f8b4dfaa32c80ddef6c0ac0e79b05cb0cbf57"

[language_servers.r_language_server]
name = "r lsp"
language = "R"
