id = "r"
name = "R"
version = "0.0.2"
schema_version = 1
authors = ["Owen Smith <ocsmit@protonmail.com>"]
description = "R languange support"
repository = "https://github.com/ocsmit/zed-r"

[grammars.r]
repository = "https://github.com/r-lib/tree-sitter-r"
commit = "c55f8b4dfaa32c80ddef6c0ac0e79b05cb0cbf57"
